### ISSUE TITLE
Add an IP logger to the website

### ISSUE THREAD

**Issue by guypagram** [Falcon-Net/falcon-net.github.io#1]
i believe it would be beneficial to track users data in order to conduct surverys. I have provided an example ip logger below:
[https://www.i-love-to.twerk.ga/?FalconNet](https://www.i-love-to.twerk.ga/?FalconNet)

**Comment by Falcon-Net** [comment]
We would never do that. I suggest you do that for GuypaGram instead, and see what reactions you get from your members.
